var searchData=
[
  ['_5fav_5fcomm_5fglobal_5fdata',['_AV_COMM_GLOBAL_DATA',['../struct__AV__COMM__GLOBAL__DATA.html',1,'']]],
  ['_5fav_5fconnection_5fcontext',['_AV_CONNECTION_CONTEXT',['../struct__AV__CONNECTION__CONTEXT.html',1,'']]],
  ['_5fav_5fconnection_5ftype',['_AV_CONNECTION_TYPE',['../KMUMcomm_8h.html#a7b3c9382b6273458d1f6ca5fcb7ff690',1,'KMUMcomm.h']]],
  ['_5fav_5fevent_5ffile_5fcreate',['_AV_EVENT_FILE_CREATE',['../struct__AV__EVENT__FILE__CREATE.html',1,'']]],
  ['_5fav_5fevent_5fimage_5fload',['_AV_EVENT_IMAGE_LOAD',['../struct__AV__EVENT__IMAGE__LOAD.html',1,'']]],
  ['_5fav_5fevent_5fnetwork',['_AV_EVENT_NETWORK',['../struct__AV__EVENT__NETWORK.html',1,'']]],
  ['_5fav_5fevent_5fprocess_5fcreate',['_AV_EVENT_PROCESS_CREATE',['../struct__AV__EVENT__PROCESS__CREATE.html',1,'']]],
  ['_5fav_5fevent_5fprocess_5fexit',['_AV_EVENT_PROCESS_EXIT',['../struct__AV__EVENT__PROCESS__EXIT.html',1,'']]],
  ['_5fav_5fevent_5fprocess_5fhandle_5fcreate',['_AV_EVENT_PROCESS_HANDLE_CREATE',['../struct__AV__EVENT__PROCESS__HANDLE__CREATE.html',1,'']]],
  ['_5fav_5fevent_5fprocess_5fhandle_5fdublicate',['_AV_EVENT_PROCESS_HANDLE_DUBLICATE',['../struct__AV__EVENT__PROCESS__HANDLE__DUBLICATE.html',1,'']]],
  ['_5fav_5fevent_5freg_5fcreate_5fopen_5fkey',['_AV_EVENT_REG_CREATE_OPEN_KEY',['../struct__AV__EVENT__REG__CREATE__OPEN__KEY.html',1,'']]],
  ['_5fav_5fevent_5fresponse',['_AV_EVENT_RESPONSE',['../struct__AV__EVENT__RESPONSE.html',1,'']]],
  ['_5fav_5fevent_5freturn_5fstatus',['_AV_EVENT_RETURN_STATUS',['../EventsKMStructures_8h.html#a2b870c639696dc62058561a5fc6aa5eb',1,'EventsKMStructures.h']]],
  ['_5fav_5fevent_5fthread_5fcreate_5fexit',['_AV_EVENT_THREAD_CREATE_EXIT',['../struct__AV__EVENT__THREAD__CREATE__EXIT.html',1,'']]],
  ['_5fav_5fevent_5fthread_5fhandle_5fcreate',['_AV_EVENT_THREAD_HANDLE_CREATE',['../struct__AV__EVENT__THREAD__HANDLE__CREATE.html',1,'']]],
  ['_5fav_5fevent_5fthread_5fhandle_5fdublicate',['_AV_EVENT_THREAD_HANDLE_DUBLICATE',['../struct__AV__EVENT__THREAD__HANDLE__DUBLICATE.html',1,'']]],
  ['_5fav_5fevent_5ftype',['_AV_EVENT_TYPE',['../KMUMcomm_8h.html#a2a199749754b09452e728ed818875e38',1,'KMUMcomm.h']]],
  ['_5fav_5fmessage',['_AV_MESSAGE',['../struct__AV__MESSAGE.html',1,'']]],
  ['_5fav_5fmessage_5ftype',['_AV_MESSAGE_TYPE',['../KMUMcomm_8h.html#ac4ff2e1adc6f5d9be278b6913dfe2ad7',1,'KMUMcomm.h']]],
  ['_5fkm_5fmessage',['_KM_MESSAGE',['../struct__KM__MESSAGE.html',1,'']]],
  ['_5fum_5freply_5fmessage',['_UM_REPLY_MESSAGE',['../struct__UM__REPLY__MESSAGE.html',1,'']]]
];
